name: brain
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - attrs=19.3.0=py_0
  - blas=1.0=mkl
  - ca-certificates=2020.12.5=h033912b_0
  - certifi=2020.12.5=py36h79c6626_1
  - cffi=1.14.0=py36h356ff06_0
  - chardet=3.0.4=py36h9f0ad1d_1006
  - cryptography=2.8=py36hc9d8292_2
  - cycler=0.10.0=py_2
  - cymem=2.0.2=py36h6de7cb9_0
  - cython-blis=0.2.4=py36h01d97ff_1
  - freetype=2.10.4=h3f75d11_0
  - idna=2.9=py_1
  - importlib-metadata=1.5.0=py36h9f0ad1d_1
  - importlib_metadata=1.5.0=1
  - intel-openmp=2019.4=233
  - joblib=0.13.2=py36_0
  - jpeg=9d=hbcb3906_0
  - jsonschema=3.2.0=py36h9f0ad1d_1
  - kiwisolver=1.1.0=py36h770b8ee_0
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - liblapack=3.8.0=14_mkl
  - libpng=1.6.37=h7cec526_2
  - libtiff=4.0.9=h79f4b77_1002
  - llvm-openmp=4.0.1=hcfea43d_1
  - matplotlib-base=3.1.1=py36h3a684a6_1
  - mkl=2019.4=233
  - mkl-service=2.0.2=py36h1de35cc_0
  - mkl_fft=1.0.12=py36h5e564d8_0
  - mkl_random=1.0.2=py36h27c97d8_0
  - murmurhash=1.0.0=py36h0a44026_0
  - ncurses=6.1=h0a44026_1
  - numpy-base=1.19.1=py36hcfb5961_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1i=h35c211d_0
  - pandas=0.25.0=py36h0a44026_0
  - pip=19.1.1=py36_0
  - plac=0.9.6=py_1
  - preshed=2.0.1=py36h6de7cb9_0
  - pycparser=2.20=py_0
  - pyopenssl=19.1.0=py_1
  - pyrsistent=0.15.7=py36h37b9a7d_1
  - pysocks=1.7.1=py36h9f0ad1d_1
  - python=3.6.9=h359304d_0
  - python-dateutil=2.8.0=py36_0
  - python_abi=3.6=1_cp36m
  - pytz=2019.1=py_0
  - readline=7.0=h1de35cc_5
  - requests=2.23.0=pyh8c360ce_2
  - scikit-learn=0.21.2=py36h27c97d8_0
  - scipy=1.3.0=py36h1410ff5_0
  - setuptools=41.0.1=py36_0
  - spacy=2.1.8=py36h770b8ee_0
  - sqlite=3.29.0=ha441bb4_0
  - srsly=0.1.0=py36h6de7cb9_0
  - thinc=7.0.8=py36h770b8ee_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.1=py36h20b66c6_1
  - tqdm=4.43.0=py_0
  - urllib3=1.25.7=py36h9f0ad1d_1
  - wasabi=0.6.0=py_0
  - wheel=0.33.4=py36_0
  - wordcloud=1.8.1=py36h6941dd6_1
  - xlrd=1.2.0=py36_0
  - xz=5.2.4=h1de35cc_4
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - boto3==1.12.22
    - botocore==1.15.22
    - cachetools==4.0.0
    - docutils==0.15.2
    - google-api-core==1.16.0
    - google-auth==1.11.3
    - google-cloud-core==1.3.0
    - google-cloud-storage==1.26.0
    - google-resumable-media==0.5.0
    - googleapis-common-protos==1.51.0
    - jmespath==0.9.5
    - matplotlib==3.2.0
    - nibabel==2.5.0
    - nilearn==0.6.2
    - numpy==1.17.0
    - pillow==8.1.0
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.6
    - rsa==4.0
    - s3transfer==0.3.3
    - six==1.12.0
    - sklearn==0.0
    - smart-open==1.10.0
prefix: /Users/sam/miniconda3/envs/brain
